/*  
FINAL STRUCTURE:

src/
  components/
    carousel/
      FeaturedCarousel.jsx
      CarouselSlide.jsx
      CarouselControls.jsx
      useCarousel.js
      index.js
    player/
      VideoPlayer.jsx
      usePopupBlocker.js
      servers.js
      index.js
    loading/
      Spinner.jsx
      SkeletonCard.jsx
      SkeletonGrid.jsx
      index.js
    icons/
      index.jsx
    MovieCard.jsx
    Navbar.jsx
    FilterBar.jsx
    Pagination.jsx
    Footer.jsx
    LazyImage.jsx
    States.jsx
    ThemeToggle.jsx
    BackToTop.jsx
  hooks/
    useMovies.js
    useGenres.js
    useFilters.js
    useMovieFetch.js
    useSearchSync.js
    useURLState.js
  lib/
    tmdb/
      client.js
      images.js
      endpoints.js
      categories.js
      index.js
    cache.js
  contexts/
    ThemeContext.jsx
  pages/
    HomePage.jsx
    MovieDetailsPage.jsx
*/